# Generated by Django 4.2.28 on 2026-02-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji or icon name', max_length=50, null=True),
        ),
    ]
