# Generated by Django 4.2.28 on 2026-02-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_icon'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE services_service CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
        ),
    ]
