# Generated by Django 4.2.28 on 2026-03-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20260215_1549'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_published'], name='services_se_is_publ_a7425f_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category'], name='services_se_categor_d1e3c4_idx'),
        ),
    ]
