# Generated by Django 4.2.27 on 2026-09-07 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0005_service_services_se_is_publ_a7425f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.TextField(default='Transforming Compliance Into Competitive Advantage', help_text='Main headline for the About Us page')),
                ('hero_subtitle', models.TextField(default='Where environmental responsibility meets business success', help_text='Subtitle/tagline for hero section')),
                ('hero_image_url', models.URLField(blank=True, default='https://res.cloudinary.com/dcrubaesi/image/upload/v1737333837/ECODEED_COLORED_LOGO_wj2yy8.png', help_text='URL to hero section image or logo')),
                ('mission_statement', models.TextField(default='At Ecodeed Consulting, we empower businesses, governments, and communities to navigate environmental compliance, implement sustainable practices, and future-proof their operations—so no dream is lost due to regulatory hurdles.', help_text='Company mission statement')),
                ('vision_statement', models.TextField(blank=True, default='', help_text='Company vision statement')),
                ('founder_name', models.CharField(default='Miriam Mukami Mwema', help_text="Founder's full name", max_length=255)),
                ('founder_bio', models.TextField(blank=True, default='', help_text="Founder's biography and background")),
                ('founder_image_url', models.URLField(blank=True, default='', help_text="URL to founder's profile photo")),
                ('values', models.JSONField(blank=True, default=list, help_text='Array of core values with name and description')),
                ('metrics', models.JSONField(blank=True, default=list, help_text='Array of impact metrics (clients served, projects, results)')),
                ('team_members', models.JSONField(blank=True, default=list, help_text='Array of team member profiles')),
                ('is_published', models.BooleanField(default=True, help_text='Whether this version is live')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aboutus_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'About Us Page',
                'verbose_name_plural': 'About Us Pages',
                'ordering': ['-updated_at'],
            },
        ),
    ]
