# Generated by Django 4.2.28 on 2026-03-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0002_contactmessage_messages_ap_created_ba8023_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The announcement message', max_length=300)),
                ('link_url', models.CharField(blank=True, default='', help_text='Internal route (e.g. /courses) or full URL', max_length=255)),
                ('link_label', models.CharField(blank=True, default='', help_text='CTA text shown next to the message (e.g. "Learn more →")', max_length=60)),
                ('is_active', models.BooleanField(default=True, help_text='Only the latest active announcement is displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
