# Generated by Django 4.2.30 on 2026-05-01 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0003_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='messages_app.emailcampaign')),
            ],
            options={
                'verbose_name': 'Email Delivery Log',
                'verbose_name_plural': 'Email Delivery Logs',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='messages_ap_campaig_13c541_idx'), models.Index(fields=['recipient_email'], name='messages_ap_recipie_751ace_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='emaildeliverylog',
            constraint=models.UniqueConstraint(fields=('campaign', 'recipient_email'), name='unique_campaign_recipient'),
        ),
    ]
