# Generated by Django 4.2.30 on 2026-05-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0004_add_email_delivery_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='If set, the campaign will be sent at this time. Leave blank to send immediately.', null=True),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=10),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['scheduled_at'], name='messages_ap_schedul_fb6ea9_idx'),
        ),
    ]
