# Generated by Django 4.2.27 on 2026-02-14 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField(max_length=500)),
                ('full_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_free', models.BooleanField(default=False)),
                ('level', models.JSONField(blank=True, default=list)),
                ('format', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=list)),
                ('curriculum', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('target_audience', models.JSONField(blank=True, default=list)),
                ('resources', models.JSONField(blank=True, default=list)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('specialized', 'Specialized'), ('masterclass', 'Masterclass'), ('webinar', 'Webinar'), ('coaching', 'Coaching'), ('compliance', 'Compliance'), ('licensing', 'Licensing')], max_length=50)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
