# Generated by Django 4.2.28 on 2026-02-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_curriculum_module_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
