# Generated by Django 4.2.28 on 2026-02-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_assignment_course_instructor_resource_livesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_certificate',
            field=models.BooleanField(default=False, help_text='Whether this course offers a certificate upon completion'),
        ),
    ]
