# Generated by Django 4.2.28 on 2026-02-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_has_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pacing_type',
            field=models.CharField(choices=[('self_paced', 'Self-Paced'), ('scheduled', 'Scheduled')], default='self_paced', help_text='How weekly content is unlocked', max_length=20),
        ),
    ]
