# Generated by Django 4.2.28 on 2026-03-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_courses_cou_categor_fec4a4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('link', 'External Link'), ('video', 'Video'), ('document', 'Document'), ('spreadsheet', 'Spreadsheet'), ('other', 'Other')], default='link', max_length=20),
        ),
    ]
