# Generated by Django 4.2.29 on 2026-03-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_resource_description_resource_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pacing_type',
            field=models.CharField(choices=[('self_paced', 'Self-Paced'), ('weekly', 'Weekly Content')], default='self_paced', help_text='How weekly content is unlocked', max_length=20),
        ),
    ]
