# Generated by Django 4.2.30 on 2026-04-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_lessoncompletion_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(help_text='Assignment instructions and requirements'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='When assignment is due (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='resource_url',
            field=models.URLField(blank=True, help_text='Link to assignment file, template, or rubric', null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.TextField(blank=True, help_text='Instructor feedback/comments', null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='grade',
            field=models.CharField(blank=True, help_text='Grade given (A+, 95/100, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='is_reviewed',
            field=models.BooleanField(default=False, help_text='Whether instructor has reviewed and graded'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submission_file_url',
            field=models.URLField(help_text='Cloudinary or S3 URL to submitted file', max_length=1000),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When student submitted'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='progress',
            field=models.JSONField(blank=True, default=dict, help_text='Tracks learning progress: lessons_completed, modules_done, etc.'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('paused', 'Paused')], default='active', help_text='Current enrollment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='Markdown/HTML text content or lecture notes'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_free_preview',
            field=models.BooleanField(default=False, help_text='Whether this lesson is free to preview'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order within module'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Vimeo/YouTube/S3 video URL', null=True),
        ),
        migrations.AlterField(
            model_name='lessoncompletion',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When student marked lesson complete'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='date_time',
            field=models.DateTimeField(help_text='When the live session occurs (UTC timezone)'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='description',
            field=models.TextField(blank=True, help_text='Session agenda, requirements, or guidelines'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='recording_url',
            field=models.URLField(blank=True, help_text='Zoom recording URL (added after session)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='zoom_link',
            field=models.URLField(help_text='Zoom meeting URL with password', max_length=1000),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, help_text='Description of resource and how to use it'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_url',
            field=models.URLField(help_text='URL to file or external resource', max_length=1000),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('link', 'External Link'), ('video', 'Video'), ('document', 'Document'), ('spreadsheet', 'Spreadsheet'), ('other', 'Other')], default='link', help_text='Type of resource for categorization and icons', max_length=20),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'is_reviewed'], name='courses_ass_assignm_d9ccb5_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['student', '-submitted_at'], name='courses_ass_student_b37ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncompletion',
            index=models.Index(fields=['enrollment', '-completed_at'], name='courses_les_enrollm_0dc972_idx'),
        ),
    ]
