# Generated by Django 4.2.30 on 2026-06-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_assignment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Name of the icon to display for the course', max_length=100, null=True),
        ),
    ]
