# Generated by Django 4.2.30 on 2026-04-12 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_payment_payments_pa_status_7ad4af_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='enrolled_by',
            field=models.ForeignKey(blank=True, help_text='Admin who manually created this payment/enrollment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_enrolled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Admin notes, e.g. reference number for manual payments'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Card'), ('mpesa', 'M-Pesa'), ('globalpay', 'GlobalPay'), ('mpesa_global', 'M-Pesa Global'), ('manual', 'Manual / Other')], max_length=20, null=True),
        ),
    ]
