# Generated by Django 4.2.28 on 2026-03-02 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('emoji', models.CharField(blank=True, default='🌍', help_text='Emoji shown alongside the category label', max_length=10)),
                ('color_class', models.CharField(blank=True, default='', help_text="Tailwind CSS class(es) for category badge, e.g. 'bg-green-100 text-green-800'", max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='canonical_url',
            field=models.URLField(blank=True, default='', help_text='Canonical URL for syndicated / cross-posted content.', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, default='', help_text='Short plain-text summary. Auto-generated from content if left blank.'),
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Pin this post to the top of listings / homepage.'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, default='', help_text='Description for search engines. Falls back to excerpt if blank.', max_length=160),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='Title for search engines. Falls back to post title if blank.', max_length=70),
        ),
        migrations.AddField(
            model_name='post',
            name='og_image',
            field=models.URLField(blank=True, default='', help_text='Open Graph image (Facebook, LinkedIn). Falls back to featured image.', max_length=1000),
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When the post goes/went live. Set automatically on first publish.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reading_time',
            field=models.PositiveSmallIntegerField(default=1, help_text='Estimated reading time in minutes (computed on save).'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='post',
            name='twitter_image',
            field=models.URLField(blank=True, default='', help_text='Twitter card image. Falls back to OG image, then featured image.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Rich HTML content (sanitized on save)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, help_text='Primary featured image URL', max_length=1000, null=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-published_at'], name='posts_post_publish_afa8cc_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', '-published_at'], name='posts_post_status_b32c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='posts_post_slug_59b922_idx'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.tag'),
        ),
    ]
