# Generated by Django 4.2.28 on 2026-03-02 03:07

import math
import re

from django.db import migrations

TAG_STRIP_RE = re.compile(r"<[^>]+>")


def _strip_html(html):
    return TAG_STRIP_RE.sub(" ", html).strip()


def _generate_excerpt(html, max_length=300):
    text = _strip_html(html)
    if len(text) <= max_length:
        return text
    truncated = text[:max_length].rsplit(" ", 1)[0]
    return truncated + "…"


def _compute_reading_time(html):
    words = len(_strip_html(html).split())
    return max(1, math.ceil(words / 200))


def backfill_posts(apps, schema_editor):
    """
    For every existing post:
    - Set status = 'published' (they were already live)
    - Set published_at = created_at
    - Compute reading_time & excerpt if empty
    - Create a Category from the old CharField value and link category_fk
    """
    Post = apps.get_model("posts", "Post")
    Category = apps.get_model("posts", "Category")

    # Build Category objects from existing unique CharField values
    category_values = (
        Post.objects.values_list("category", flat=True).distinct()
    )
    cat_map = {}  # "climate-change" -> Category instance
    for idx, cat_value in enumerate(category_values):
        if cat_value:
            cat_obj, _ = Category.objects.get_or_create(
                name=cat_value.replace("-", " ").title(),
                defaults={
                    "slug": cat_value.lower().replace(" ", "-"),
                    "order": idx,
                },
            )
            cat_map[cat_value] = cat_obj

    for post in Post.objects.all():
        changed = False

        if post.status != "published":
            post.status = "published"
            changed = True

        if not post.published_at and post.created_at:
            post.published_at = post.created_at
            changed = True

        if not post.excerpt and post.content:
            post.excerpt = _generate_excerpt(post.content)
            changed = True

        if post.content:
            rt = _compute_reading_time(post.content)
            if post.reading_time != rt:
                post.reading_time = rt
                changed = True

        # Link category_fk from the old CharField value
        if post.category and post.category in cat_map and not post.category_fk_id:
            post.category_fk = cat_map[post.category]
            changed = True

        if changed:
            post.save(update_fields=[
                "status", "published_at", "excerpt",
                "reading_time", "category_fk",
            ])


def reverse_noop(apps, schema_editor):
    pass  # no reverse needed


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_category_tag_post_canonical_url_post_excerpt_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_posts, reverse_noop),
    ]
