# Generated by Django 4.2.28 on 2026-03-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_backfill_existing_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text="When to auto-publish a scheduled post. Required when status='scheduled'.", null=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'scheduled_for'], name='posts_post_status_d53e9b_idx'),
        ),
    ]
