# Generated by Django 4.2.28 on 2026-03-03 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_lessoncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='If set, this comment is a reply to another comment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('spam', 'Spam'), ('rejected', 'Rejected')], db_index=True, default='approved', help_text='Moderation status. Default APPROVED for backward compat; switch default to PENDING once a review workflow is in place.', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='Comment body (HTML sanitized on save).', max_length=2000),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', '-created_at'], name='comments_co_post_id_3d4abc_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'status', '-created_at'], name='comments_co_post_id_6d9a79_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='comments_co_user_id_4d6386_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='comments_co_parent__fdf1ec_idx'),
        ),
    ]
