# Generated by Django 4.2.28 on 2026-03-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_add_threading_moderation_sanitization'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lessoncomment',
            index=models.Index(fields=['lesson', '-created_at'], name='comments_le_lesson__804e2d_idx'),
        ),
    ]
